### ISSUE TITLE
in sync_bills     body['properties']['金额']['number'] = float(bill[5].replace('¥', ''))

### ISSUE THREAD

**Issue by wangke8023** [edge-sky/Bills-save#7]
好奇怪，微信导入成功了一半，看日志是金额的时候取到的值是“支出”，理论上遍历取值，要么全错，要么全对，看代码也没啥问题，金额取值第五列没毛病，不过不太懂python，麻烦大佬看下，可能是什么情况？
![image](https://github.com/user-attachments/assets/5675a146-5181-4a9b-be71-4fb903657ae0)
Traceback (most recent call last):
  File "/home/notion/Bills-save/main.py", line 58, in <module>
    is_successes = sync_bills(server, platform, wechat_data(path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notion/Bills-save/notion.py", line 139, in sync_bills
    body['properties']['金额']['number'] = float(bill[5].replace('¥', ''))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '支出'
![image](https://github.com/user-attachments/assets/cd93d324-9d0e-4bc9-b5af-0144a7f050bf)

**Comment by edge-sky** [comment]
是有点奇怪，数据清是按照我导出的微信账单格式设计。你的报错看起来是某一个次交易的格式和我设计的不匹配，具体表现为那条记录中&nbsp;&ldquo;支出&rdquo;&nbsp;前多了一个项，但我还没有遇到过这种情况，需要你手动检查一下该.CVS&nbsp;文件是否有什么不一样的地方。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月17日(周四) 下午2:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [edge-sky/Bills-save] in sync_bills     body['properties']['金额']['number'] = float(bill[5].replace('&yen;', '')) (Issue #7)




 
好奇怪，微信导入成功了一般，看日志是金额的时候取到的值是“支出”，理论上遍历取值，要么全错，要么全对，看代码也没啥问题，金额取值第五列没毛病，不过不太懂python，麻烦大佬看下，可能是什么情况？
 image.png (view on web)
 Traceback (most recent call last):
 File "/home/notion/Bills-save/main.py", line 58, in 
 is_successes = sync_bills(server, platform, wechat_data(path))
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/notion/Bills-save/notion.py", line 139, in sync_bills
 body['properties']['金额']['number'] = float(bill[5].replace('¥', ''))
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ValueError: could not convert string to float: '支出'
 image.png (view on web)
 
&mdash;

**Comment by wangke8023** [comment]
> 是有点奇怪，数据清是按照我导出的微信账单格式设计。你的报错看起来是某一个次交易的格式和我设计的不匹配，具体表现为那条记录中&nbsp;&ldquo;支出&rdquo;&nbsp;前多了一个项，但我还没有遇到过这种情况，需要你手动检查一下该.CVS&nbsp;文件是否有什么不一样的地方。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年10月17日(周四) 下午2:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [edge-sky/Bills-save] in sync_bills body['properties']['金额']['number'] = float(bill[5].replace('&yen;', '')) (Issue #7) 好奇怪，微信导入成功了一般，看日志是金额的时候取到的值是“支出”，理论上遍历取值，要么全错，要么全对，看代码也没啥问题，金额取值第五列没毛病，不过不太懂python，麻烦大佬看下，可能是什么情况？ image.png (view on web) Traceback (most recent call last): File "/home/notion/Bills-save/main.py", line 58, in is_successes = sync_bills(server, platform, wechat_data(path)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/notion/Bills-save/notion.py", line 139, in sync_bills body['properties']['金额']['number'] = float(bill[5].replace('¥', '')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: could not convert string to float: '支出' image.png (view on web) &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我逐列输入值，发现apple的账单商品这一列有点长，不过在excel中是一列，不知道为啥在程序中被识别成了两列？
![image](https://github.com/user-attachments/assets/d1c4a694-b6f9-49aa-9139-49fbe9ac9b55)
![image](https://github.com/user-attachments/assets/ecd43768-de29-4c29-889d-9d1d93259024)

**Comment by edge-sky** [comment]
应该是那个换行导致的，设计的时候没有考虑到这种情况，也没遇到过。后面有时间再考虑改进，你也可以自行尝试修复


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月17日(周四) 下午4:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [edge-sky/Bills-save] in sync_bills     body['properties']['金额']['number'] = float(bill[5].replace('&yen;', '')) (Issue #7)




  
是有点奇怪，数据清是按照我导出的微信账单格式设计。你的报错看起来是某一个次交易的格式和我设计的不匹配，具体表现为那条记录中 “支出” 前多了一个项，但我还没有遇到过这种情况，需要你手动检查一下该.CVS 文件是否有什么不一样的地方。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年10月17日(周四) 下午2:56 收件人: @.&gt;; 抄送: @.&gt;; 主题: [edge-sky/Bills-save] in sync_bills body['properties']['金额']['number'] = float(bill[5].replace('¥', '')) (Issue #7) 好奇怪，微信导入成功了一般，看日志是金额的时候取到的值是“支出”，理论上遍历取值，要么全错，要么全对，看代码也没啥问题，金额取值第五列没毛病，不过不太懂python，麻烦大佬看下，可能是什么情况？ image.png (view on web) Traceback (most recent call last): File "/home/notion/Bills-save/main.py", line 58, in is_successes = sync_bills(server, platform, wechat_data(path)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/notion/Bills-save/notion.py", line 139, in sync_bills body['properties']['金额']['number'] = float(bill[5].replace('¥', '')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: could not convert string to float: '支出' image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
我逐列输入值，发现apple的账单商品这一列有点长，不过在excel中是一列，不知道为啥在程序中被识别成了两列？
 image.png (view on web)
 image.png (view on web)
 
&mdash;

**Comment by wangke8023** [comment]
> 应该是那个换行导致的，设计的时候没有考虑到这种情况，也没遇到过。后面有时间再考虑改进，你也可以自行尝试修复
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年10月17日(周四) 下午4:06 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [edge-sky/Bills-save] in sync_bills body['properties']['金额']['number'] = float(bill[5].replace('&yen;', '')) (Issue #7) 是有点奇怪，数据清是按照我导出的微信账单格式设计。你的报错看起来是某一个次交易的格式和我设计的不匹配，具体表现为那条记录中 “支出” 前多了一个项，但我还没有遇到过这种情况，需要你手动检查一下该.CVS 文件是否有什么不一样的地方。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年10月17日(周四) 下午2:56 收件人: @.&gt;; 抄送: @.&gt;; 主题: [edge-sky/Bills-save] in sync_bills body['properties']['金额']['number'] = float(bill[5].replace('¥', '')) (Issue #7) 好奇怪，微信导入成功了一般，看日志是金额的时候取到的值是“支出”，理论上遍历取值，要么全错，要么全对，看代码也没啥问题，金额取值第五列没毛病，不过不太懂python，麻烦大佬看下，可能是什么情况？ image.png (view on web) Traceback (most recent call last): File "/home/notion/Bills-save/main.py", line 58, in is_successes = sync_bills(server, platform, wechat_data(path)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/notion/Bills-save/notion.py", line 139, in sync_bills body['properties']['金额']['number'] = float(bill[5].replace('¥', '')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: could not convert string to float: '支出' image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 我逐列输入值，发现apple的账单商品这一列有点长，不过在excel中是一列，不知道为啥在程序中被识别成了两列？ image.png (view on web) image.png (view on web) &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

![image](https://github.com/user-attachments/assets/2796eaf4-627a-4bed-a14d-578b7865a786)
没有换行，是这个地方的代码，你对列值做了“，”的数组截取，不知道是什么用意，感觉可以去掉，不然列值里带逗号的，就会被处理成两列。我先去掉了，如果有什么不妥，麻烦告知一下有什么坑，谢谢

**Comment by edge-sky** [comment]
原来是&nbsp;','的问题。但我原先的用意是因为&nbsp;.CVS&nbsp;是以逗号分隔的(你用文本打开它就会发现)，可以尝试使用&nbsp;pandas&nbsp;之类三方库处理。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月17日(周四) 下午4:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [edge-sky/Bills-save] in sync_bills     body['properties']['金额']['number'] = float(bill[5].replace('&yen;', '')) (Issue #7)




  
应该是那个换行导致的，设计的时候没有考虑到这种情况，也没遇到过。后面有时间再考虑改进，你也可以自行尝试修复
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年10月17日(周四) 下午4:06 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [edge-sky/Bills-save] in sync_bills body['properties']['金额']['number'] = float(bill[5].replace('¥', '')) (Issue #7) 是有点奇怪，数据清是按照我导出的微信账单格式设计。你的报错看起来是某一个次交易的格式和我设计的不匹配，具体表现为那条记录中 “支出” 前多了一个项，但我还没有遇到过这种情况，需要你手动检查一下该.CVS 文件是否有什么不一样的地方。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年10月17日(周四) 下午2:56 收件人: @.&gt;; 抄送: @.&gt;; 主题: [edge-sky/Bills-save] in sync_bills body['properties']['金额']['number'] = float(bill[5].replace('¥', '')) (Issue #7) 好奇怪，微信导入成功了一般，看日志是金额的时候取到的值是“支出”，理论上遍历取值，要么全错，要么全对，看代码也没啥问题，金额取值第五列没毛病，不过不太懂python，麻烦大佬看下，可能是什么情况？ image.png (view on web) Traceback (most recent call last): File "/home/notion/Bills-save/main.py", line 58, in is_successes = sync_bills(server, platform, wechat_data(path)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/notion/Bills-save/notion.py", line 139, in sync_bills body['properties']['金额']['number'] = float(bill[5].replace('¥', '')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: could not convert string to float: '支出' image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 我逐列输入值，发现apple的账单商品这一列有点长，不过在excel中是一列，不知道为啥在程序中被识别成了两列？ image.png (view on web) image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
image.png (view on web)
 没有换行，是这个地方的代码，你对列值做了“，”的数组截取，不知道是什么用意，感觉可以去掉，不然列值里带逗号的，就会被处理成两列。我先去掉了，如果有什么不妥，麻烦告知一下有什么坑，谢谢
 
&mdash;

**Comment by bdingtech** [comment]
我也碰到了这个问题，大佬们最后怎么解决的

**Comment by bdingtech** [comment]
Traceback (most recent call last):
  File "/Users/pudding/dev/Bills-save/main.py", line 57, in <module>
    is_successes = sync_bills(server, platform, wechat_data(path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pudding/dev/Bills-save/notion.py", line 139, in sync_bills
    body['properties']['金额']['number'] = float(bill[5].replace('¥', ''))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '支付[100.0]元"'

![CleanShot 2024-10-23 at 13 48 11@2x](https://github.com/user-attachments/assets/98450af0-54ef-471b-b649-aeace6c9b7fb)
微信真的奇奇怪怪的备注一大堆

**Comment by wangke8023** [comment]
> -----------谷歌翻译-----------回溯（最近一次调用最后一次）：文件“/Users/pudding/dev/Bills-save/main.py”，第 57 行，位于is_successes =sync_bills(服务器、平台、wechat_data(路径))^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^文件“/Users/pudding/dev/Bills-save/notion.py”，第 139 行，在sync_bills 中body['properties']['金额']['number'] = float(bill[5].replace('¥', ''))^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ValueError: 无法将字符串转换为浮点数: '支付[100.0]元"'
> 
> ![CleanShot 2024-10-23 at 13 48 11@2x](https://private-user-images.githubusercontent.com/29543092/379119486-98450af0-54ef-471b-b649-aeace6c9b7fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjM4MjQsIm5iZiI6MTcyOTY2MzUyNCwicGF0aCI6Ii8yOTU0MzA5Mi8zNzkxMTk0ODYtOTg0NTBhZjAtNTRlZi00NzFiLWI2NDktYWVhY2U2YzliN2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2MDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNjY1NDg2Nzg0MzczZWFmOWI2ODY5YjkyMzc4NzAxYWIwNjRhZTQ1NjA0OWNhN2Q4ZWI0MDI0ZGU4OTBkNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lwzv7hCcQHUIOzOvNUm_LT7m6T73JQyg_UaVj8yZiVM) 微信真的奇奇怪怪的备注一大堆

使用python内置的csv模块进行解析，不要自己分割字符串就行了
![image](https://github.com/user-attachments/assets/f4033f8f-00f0-49ae-ac51-3c94b7b95fc9)

**Comment by bdingtech** [comment]
谢谢啦。我问了ChatGPT，已经解决这个问题了！
![CleanShot 2024-10-23 at 14 09 37@2x](https://github.com/user-attachments/assets/4d91cf90-b70d-4e99-a1e0-e67ca26706a6)
